name: Sama_app
description: "Learn Japanese basics in a fun and interactive way."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  audioplayers: ^6.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10

# 🔥 ICON CONFIG (صح)
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/SamaIcon.png"
  adaptive_icon_background: "#6D4C41"
  adaptive_icon_foreground: "assets/icon/SamaIcon.png"

# 🔥 SPLASH CONFIG
flutter_native_splash:
  color: "#6D4C41"
  image: assets/icon/SamaIcon.png

  android_12:
    image: assets/icon/SamaIcon.png
    color: "#6D4C41"

flutter:
  uses-material-design: true

  assets:
    - assets/images/numbers/
    - assets/images/colors/
    - assets/images/family_members/
    - assets/sounds/colors/
    - assets/sounds/family_members/
    - assets/sounds/numbers/
    - assets/sounds/phrases/
    # ❌ تم حذف icon من assets لأنه مش مطلوب هنا